### ISSUE TITLE
operator() on function objects need to be const (VS2017)

### ISSUE THREAD

**Issue by akoolenbourke** [jbandela/stackless_coroutine#2]
Not sure if this library is still being worked on but I wanted to use some function objects that stored some state that mutated as the co-routine looped. However operator() has to be const or else I get the error
`error C3848: expression having type 'const signal_cv' would lose some const-volatile qualifiers in order to call 'auto signal_cv::operator ()<DC,Value>(Context &,Vars &)`

The code reads:

 template<typename Context, typename Vars>
 auto operator()(Context &c, Vars &v)
 {
     cv.notify_all();
     return c.do_next();
 }

I can get around it with mutable members but I was just wondering if I've missed something, it's as designed or a VS issue?

Thanks

**Comment by jbandela** [comment]
This behavior is by design. All the instances of a stackless coroutines
share a constant static tuple of the lamda functions, this they are
required to be const. You need to out all your mutable state inside Vars,
and access it via v.state.

Let me know if you have more questions.

**Comment by akoolenbourke** [comment]
Thanks john. I discovered the static tuple shortly after posting when I found another weird issue (Which is by design too I imagine).

I had two coroutines that were identical and it always just executed the first instance due to static-ness.
