### ISSUE TITLE
Recommended way to mix do_async and do_next

### ISSUE THREAD

**Issue by akoolenbourke** [jbandela/stackless_coroutine#3]
I'm writing a function object that needs to check a state variable when it starts and if a condition is met simply continue on the pipeline. If the condition is false I need to issue an async operation (ASIO). Because I'm using async I need to return context.do_async(), however this means the return value in an auto operator() is different than earlier where it was context.do_next().

Is there a way to handle these cases elegantly?

Thanks

**Comment by jbandela** [comment]
Is it possible to show a little more code as an example?

**Comment by akoolenbourke** [comment]
Here's a bit of code that demonstrates the issue:
 ```       
struct my_operation
template<typename Context, typename Vars>
    auto operator()(Context &context, Vars &v) const
    {
        auto &client_stream = v.client_stream;
        auto &buffer = v.buffer;
        if (buffer.size())
        {
            return context.do_next();  // We already have some in buffer, just carry on to next stage
        }
        auto b = buffer.prepare(std::min(DEFAULT_BUFFER_SIZE - buffer.size(), DEFAULT_BUFFER_SIZE));
        client_stream.async_read_some(b, context);
        return context.do_async(); // This return type is different to the do_next() above.
    }
}```

I am going to have to work around something because async_read_some will not complete until it gets something (or error/close of course)

I am thinking that I will have to post the context to the executor so it's called async and then I can do context.do_async(), in my call but I was hoping to avoid the overhead of that.

Thanks

**Comment by jbandela** [comment]
In this case you want to use make_if.

make_if([](auto& context, auto& v){return buffer.size() >0;},
//then
std::make_tuple([](auto&&...){//do nothing}),
//else
std::make_tuple([](auto& context, auto& v){
//Do async stuff
return context.do_async();
},
//handler for async callback
);

Take a look at test.cpp for examples of using make_if

Hope this helps
